# Comments in GraphQL strings (such as this one) start with the hash (#) symbol.

# both server and client and database should agree to this
# be aware that either types or database can change. there's no strict guarantee that on the type.
type Book {
  id: String
  title: String
  author: String
}

type BookQueries {
  books: [Book]
  book(id: String!): Book
}

type BookMutations {
  addBook(title: String!, author: String!): Book
}
