# Comments in GraphQL strings (such as this one) start with the hash (#) symbol.

# both server and client and database should agree to this
# be aware that either types or database can change. there's no strict guarantee that on the type.
type Book {
  id: String
  title: String
  author: String
}

extend type Query {
  Book_books: [Book]
  Book_book(id: String!): Book
}

extend type Mutation {
  Book_addBook(title: String!, author: String!): Book
}

# testing subscription
type BookPingResult {
  message: String!
}

extend type Subscription {
  Book_ping: BookPingResult! # testing subscription
}
