input NicknameExistsInput {
  nickname: String!
}

type NicknameExistsOutput {
  exists: Boolean!
  sanitizedNickname: String!
}

extend type Query {
  User_nicknameExists(input: NicknameExistsInput!): NicknameExistsOutput!
}
