input VerificationCodeSubmitInput {
  verificationCodeRequestToken: String!
  verificationCode: String!
}

type VerificationCodeSubmitOutput {
  verificationCodeSubmitToken: String!
}

enum VerificationCodeSubmitError {
  VERIFICATION_TIME_EXPIRED
  INVALID_VERIFICATION_STATE
  VERIFICATION_CODE_MISMATCH
  RATE_LIMITED
}
