input SignInInput {
  authId: String! # can be phoneNumber, email, or userId, etc.
  password: String!
}

type SignInOutput {
  user: User!
}

enum SignInError {
  INVALID_PASSWORD_OR_USER_DOESNT_EXIST
  RATE_LIMITED
}
