enum AccountType {
  SELLER
  USER
}

type UserPublicFields {
  nickname: String!
  accountType: AccountType!
}

type UserPrivateFields {
  isAdmin: Boolean!
}

type User {
  userId: String!
  public: UserPublicFields!
  private: UserPrivateFields!
}
