import React from 'react'
import Head from 'next/head'
import '@/src/styles/global/_global-styles.scss'
import type { Metadata } from 'next'
import { ErrorBoundary } from '@/src/components/error-boundary'
import { ApolloProvider } from '@/src/framework/apollo/client'
import { ForceRSC } from '@/src/components/force-rsc'
import { ToastProvider } from '@components/toast-provider'
import { PushProvider } from '@hooks/use-push'
import { AuthProvider } from '@hooks/use-auth/client'
// initialize rsc client
import '@framework/apollo/rsc'
import '@util/cookie/rsc'
import '@hooks/use-auth/rsc'
// initialize app methods
import '@framework/app'
import { InjectSafeAreaInset } from '@framework/app/inject-safe-area-inset'

console.log(`NODE_ENV : ${process.env.NODE_ENV}`)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Head>
        <link rel="manifest" href="manifest.json" />
        <link
          rel="preload"
          href="/fonts/nanum-gothic/nanum-gothic-400.woff2"
          as="font"
          type="font/woff2"
        />
        <link
          rel="preload"
          href="/fonts/nanum-gothic/nanum-gothic-700.woff2"
          as="font"
          type="font/woff2"
        />
        <link
          rel="preload"
          href="/fonts/nanum-gothic/nanum-gothic-800.woff2"
          as="font"
          type="font/woff2"
        />
        <InjectSafeAreaInset />
      </Head>
      <html lang="kr">
        <body>
          <ErrorBoundary>
            <ApolloProvider>
              <AuthProvider>
                <PushProvider>{children}</PushProvider>
              </AuthProvider>
              <ToastProvider />
              <ForceRSC />
            </ApolloProvider>
          </ErrorBoundary>
        </body>
      </html>
    </>
  )
}
