import React from 'react'
import '#src/styles/global/_global-styles.scss'
import type { Metadata } from 'next'
import { ApolloProvider } from '#src/framework/apollo/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloProvider>
      <html lang="kr">
        <body>{children}</body>
      </html>
    </ApolloProvider>
  )
}
