import React from 'react'
import Head from 'next/head'
import '@/src/styles/global/_global-styles.scss'
import type { Metadata } from 'next'
import { ErrorBoundary } from '@/src/components/error-boundary'
import { ApolloProvider } from '@/src/framework/apollo/client'
import { ForceRSC } from '@/src/components/force-rsc'
import { ToastProvider } from '@components/toast-provider'
// initialize rsc client
import '@framework/apollo/rsc'
import '@util/cookie/rsc'

console.log(`NODE_ENV : ${process.env.NODE_ENV}`)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Head>
        <link
          rel="preload"
          href="/fonts/nanum-gothic/nanum-gothic-400.woff2"
          as="font"
          type="font/woff2"
        />
        <link
          rel="preload"
          href="/fonts/nanum-gothic/nanum-gothic-700.woff2"
          as="font"
          type="font/woff2"
        />
        <link
          rel="preload"
          href="/fonts/nanum-gothic/nanum-gothic-800.woff2"
          as="font"
          type="font/woff2"
        />
      </Head>
      <html lang="kr">
        <body>
          <ErrorBoundary>
            <ApolloProvider>
              {children}
              <ToastProvider />
              <ForceRSC />
            </ApolloProvider>
          </ErrorBoundary>
        </body>
      </html>
    </>
  )
}
