input PasswordResetInput {
  newPassword: String!
  verificationCodeSubmitToken: String!
}

type PasswordResetOutput {
  user: User!
}

enum PasswordResetError {
  VERIFICATION_TIME_EXPIRED
  INVALID_METHOD
  INVALID_STATE
  RATE_LIMITED
}
