input PasswordResetInput {
  newPassword: String!
  verificationCodeSubmitToken: String!
}

type PasswordResetOutput {
  user: User!
}

enum PasswordResetError {
  VERIFICATION_TIME_EXPIRED
  INVALID_METHOD
  INVALID_STATE
  RATE_LIMITED
  ACCOUNT_NOT_EXISTS
}

extend type Mutation {
  Auth_passwordReset(input: PasswordResetInput!): PasswordResetOutput!
}
