# Comments in GraphQL strings (such as this one) start with the hash (#) symbol.

# both server and client and database should agree to this
# be aware that either types or database can change. there's no strict guarantee that on the type.
type Book {
  title: String
  author: String
}

# client queries using this
# server defines resolvers using this
type Query {
  books: [Book]
  book(id: String!): Book
}
