input SignUpInput {
  # authId provided via verificationCodeSubmitToken
  password: String!
  nickname: String!
  accountType: AccountType!
  verificationCodeSubmitToken: String!
}

type SignUpOutput {
  user: User!
}

enum SignUpError {
  VERIFICATION_TIME_EXPIRED
  INVALID_METHOD
  INVALID_STATE
  ACCOUNT_ALREADY_EXISTS
  NICKNAME_ALREADY_EXISTS
  RATE_LIMITED
}
