input VerificationCodeRequestInput {
  method: VerificationRequiredAuthMethod!
  verificationService: VerificationService!
  authId: String! # request verification for the following authId
}

type VerificationCodeRequestOutput {
  authId: String!
  verificationCodeRequestToken: String!
}

enum VerificationCodeRequestError {
  RATE_LIMITED
}

extend type Mutation {
  Auth_verificationCodeRequest(
    input: VerificationCodeRequestInput!
  ): VerificationCodeRequestOutput!
}
