# Methods that require verification code
enum VerificationRequiredAuthMethod {
  SIGN_IN
  SIGN_UP
  PASSWORD_RESET
}

# list verification service types you use!
enum VerificationService {
  BIZMSG_SMS
  BIZMSG_ALIMTALK
  # EMAIL
}

enum VerificationCodeState {
  VERIFICATION_CODE_REQUEST
  VERIFICATION_CODE_SUBMIT
}

enum AuthProviderService {
  KAKAO
}
