enum AuthMethod {
  SIGN_IN
  SIGN_UP
  PASSWORD_RESET
  # PASSWORD_CHANGE
  # SIGN_OUT
  # DELETE_ACCOUNT
  # ADD_SIGN_IN_METHOD
}

# list verification service types you use!
enum VerificationService {
  BIZMSG_SMS
  BIZMSG_ALIMTALK
  # EMAIL
}

enum VerificationCodeState {
  VERIFICATION_CODE_REQUEST
  VERIFICATION_CODE_SUBMIT
}
